// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh6lfdG6K_l-_oo_cWvgZuc5ynjp-Gnw4',
    appId: '1:761357065237:web:c68653d8d5d6c1de06421c',
    messagingSenderId: '761357065237',
    projectId: 'vehiman-e0ab0',
    authDomain: 'vehiman-e0ab0.firebaseapp.com',
    storageBucket: 'vehiman-e0ab0.appspot.com',
    measurementId: 'G-NS9VGT239S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuxzbuV5HWBP5TVnawdQg_Kuf2WwuDwck',
    appId: '1:761357065237:android:b91dc62d0429fd7906421c',
    messagingSenderId: '761357065237',
    projectId: 'vehiman-e0ab0',
    storageBucket: 'vehiman-e0ab0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh06jvPNnjVS9bY1uE7rF4qOp_RXinyEs',
    appId: '1:761357065237:ios:18d69605b73d37a606421c',
    messagingSenderId: '761357065237',
    projectId: 'vehiman-e0ab0',
    storageBucket: 'vehiman-e0ab0.appspot.com',
    iosBundleId: 'com.example.vehiman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh06jvPNnjVS9bY1uE7rF4qOp_RXinyEs',
    appId: '1:761357065237:ios:fbcda99cf9f147fb06421c',
    messagingSenderId: '761357065237',
    projectId: 'vehiman-e0ab0',
    storageBucket: 'vehiman-e0ab0.appspot.com',
    iosBundleId: 'com.example.vehiman.RunnerTests',
  );
}
